// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdTyhF5nmrRuK9YmDMtmCNvk7YJi4YI9k',
    appId: '1:240030158552:web:e8671f990bc3f42d9451ad',
    messagingSenderId: '240030158552',
    projectId: 'petsy-mobdev',
    authDomain: 'petsy-mobdev.firebaseapp.com',
    storageBucket: 'petsy-mobdev.firebasestorage.app',
    measurementId: 'G-1C8EEC0Q9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALoC3uixNhKEyclHo9p-Me9WD0DIf3auA',
    appId: '1:240030158552:android:ee0db92f70650dba9451ad',
    messagingSenderId: '240030158552',
    projectId: 'petsy-mobdev',
    storageBucket: 'petsy-mobdev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk_jNfcGK47zQmRypbbmL_qizlldvj9zA',
    appId: '1:240030158552:ios:69de5e5a30f3c6b29451ad',
    messagingSenderId: '240030158552',
    projectId: 'petsy-mobdev',
    storageBucket: 'petsy-mobdev.firebasestorage.app',
    iosBundleId: 'com.example.petsy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk_jNfcGK47zQmRypbbmL_qizlldvj9zA',
    appId: '1:240030158552:ios:69de5e5a30f3c6b29451ad',
    messagingSenderId: '240030158552',
    projectId: 'petsy-mobdev',
    storageBucket: 'petsy-mobdev.firebasestorage.app',
    iosBundleId: 'com.example.petsy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdTyhF5nmrRuK9YmDMtmCNvk7YJi4YI9k',
    appId: '1:240030158552:web:4050b2f112f1dfee9451ad',
    messagingSenderId: '240030158552',
    projectId: 'petsy-mobdev',
    authDomain: 'petsy-mobdev.firebaseapp.com',
    storageBucket: 'petsy-mobdev.firebasestorage.app',
    measurementId: 'G-QTX44E7EET',
  );
}
