import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Add this line
// 1. Make sure this import path matches where you saved the file!
import 'package:petsy/features/splash/presentation/screens/splash_screen.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

void main() async {
  // 1. Ensure Flutter engine is initialized
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase with your platform options
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Petsy',
      // 2. Using your splash screen as the starting point
      home: const PetsySplashScreen(),
    );
  }
}
